define([], function() {
  'use strict';

  return {
    categories: [{
      value: 'phone',
      text: '手机',
      ico: 'phone.png'
    }, {
      value: 'android',
      text: '安卓手机',
      ico: 'android.png'
    }, {
      value: 'iphone',
      text: '苹果手机',
      ico: 'iphone.png'
    }, {
      value: 'wp',
      text: 'Windows手机',
      ico: 'wp.png'
    }, {
      value: 'pad',
      text: '平板',
      ico: 'phone.png'
    }, {
      value: 'notebook',
      text: '笔记本电脑',
      ico: 'note-book.png'
    }, {
      value: 'pc',
      text: '台式电脑',
      ico: 'pc.png'
    }, {
      value: 'disk',
      text: '存储',
      ico: 'disk.png'
    }, {
      value: 'usb',
      text: '移动存储',
      ico: 'usb.png'
    }, {
      value: 'dataduplicate',
      text: '数据备份',
      ico: 'data-duplicate.png'
    }, {
      value: 'dataencrypt',
      text: '数据加密',
      ico: 'data-encrypt.png'
    }, {
      value: 'dataprotect',
      text: '数据保护',
      ico: 'data-protect.png'
    }, {
      value: 'datarecovery',
      text: '数据恢复',
      ico: 'data-recovery.png'
    }, {
      value: 'other',
      text: '其他',
      ico: 'other.png'
    }],
    categoryListID: 'categoryList',
  };
});